- installations.md
I just noticed a few minor things in the installation instructions and fixed those.
> Tidy installation instructions

- src/client/components/Loader/Loader.js
- src/client/components/Loader/Loader.stories.js
- src/client/components/Loader/Loader.style.css
this PR for Adding loader to project 
Fixes #13 
i have run it on **http://localhost:3007/?path=/story/loader--loader**
>  adding loader to project

- src/server/migrations/20201115193601_create_skills_table.js
- src/server/seeds/development/SkillsTable.js
- src/server/seeds/development/skills.js
inserted skills table in database.
Fixes #24 
in MySQL
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] I have made corresponding changes to the documentation
> create db skills table

- README.md
Add the link of the DB Diagram to the README.md
> Adding DB Diagram link to the README.md

- package-lock.json
- package.json
- src/client/components/DateTime/DateTime.js
- src/client/components/DateTime/DateTime.stories.js
- src/client/components/DateTime/DateTime.styles.css
Added the DateTime component through installing React DateTime package
Fixes #20 
can be tested through storybook
> DateTime component

- src/client/components/Radio/ButtonRadio.css
- src/client/components/Radio/ButtonRadio.js
- src/client/components/Radio/ButtonRadio.stories.js
Add Radio button Component. also styled it and added storybook
Fixes #11  (issue no 11)
It can be seen in StoryBook
> Add Radio component with storybook

- src/client/App.js
- src/client/components/Route404/Route404.js
- src/client/components/Route404/index.js
Fixes #60  (issue)
- [x ] I have performed a self-review of my own code
> Add Route404 component

- src/client/App.js
- src/client/containers/404Page/404Page.component.js
- src/client/containers/EventsPage/EventsPage.component.js
- src/client/containers/LoginPage/LoginPage.component.js
- src/client/containers/ProfilePage/ProfilePage.component.js
- src/client/containers/RegistrationPage/RegistrationPage.component.js
- src/client/containers/SelectionPage/SelectionPage.component.js
Creates dummy pages (for naming consistency).
Fixes #61 
These are just empty pages with a respective title.
> Dummy pages created

- src/client/components/Modal/Modal.css
- src/client/components/Modal/Modal.js
- src/client/components/Modal/Modal.stories.js
Modal view with title and closing X button created
Fixes # (19)
- [ x] I have performed a self-review of my own code
> Storybook: Modal View with Title and closing button X #19

- package-lock.json
- package.json
- src/client/containers/SignUp/index.js
Replace pre-commit hook that lints and fixes prettier issues.
Make a style error and try committing :) No error should be raised.
> Add lint-staged and replace pre-commit hook.

- src/client/components/StudyGroupLogo/StudyGroupLogo.styles.css
this PR addresses the corrections for study group logo (issue #10). 
Fixes #10
> correction-study group logo

- src/client/components/Card/Card.js
- src/client/components/Card/Card.stories.js
- src/client/components/Card/Card.styles.css
This PR is to create a storybook card  with Title and Text .
Fixes # 15
it is tested in storybook and is working **http://localhost:6007/?path=/story/title-and-text-card--component**
> Added Title and text card issue #15

- src/client/components/Button/Button.js
- src/client/components/Button/Button.stories.js
- src/client/components/Button/Button.styles.css
- src/client/components/CardWithEventsOrStudyGroups/CardWithEventsOrStudyGroups.js
- src/client/components/CardWithEventsOrStudyGroups/CardWithEventsOrStudyGroups.stories.js
- src/client/components/CardWithEventsOrStudyGroups/CardWithEventsOrStudyGroups.styles.css
- src/client/components/EventCardText/EventCardText.js
- src/client/components/EventCardText/EventCardText.stories.js
- src/client/components/EventCardText/EventCardText.styles.css
This is modification to PR #89 . Removed absolute position and used flexbox.
so please ignore PR #89
Fixes #59 
> Modification to PR #89 card with event or study group

- src/server/migrations/20201125101025_create_roles_table.js
- src/server/migrations/20201129124000_create_user_roles_table.js
- src/server/migrations/20201129124100_create_groups_table.js
Users, Organisations, Groups, Roles, and User_Roles - Group Pink
In our group @daxiousm, @AkoAyukngat, and @Pallabi-ghosh we all are working together. 
Fixes #94 ---original issue # (63)
we tested in our local MySql database. This is working fine now.
> New created PR for tables Roles,user_roles and groups added -Group Pink

- src/server/api/controllers/modules.controller.js
- src/server/api/lib/utils/pagination.js
- src/server/api/lib/utils/winston.js
- src/server/api/routes/api-router.js
- src/server/api/routes/modules.router.js
- src/server/app.js
- src/server/migrations/20201129123530_create_organizations_table.js
- src/server/migrations/20201129123900_create_users_table.js
- src/server/migrations/20201129222522_create_questions_table.js
Running `npm run code:clean` shows some changes, so those files should probably be updated.
No testing.
> Running code:clean

- src/server/api/controllers/skills.controller.js
- src/server/api/routes/api-router.js
- src/server/api/routes/skills.router.js
This API retrieves list of skills including id and name.
Fixes #101 
Tested through swagger
> API: Endpoint for retrieving the list of skills

- src/client/components/footer/footer.styles.css
- src/client/containers/404Page/404Page.component.js
- src/client/containers/404Page/404Page.stories.js
- src/client/containers/404Page/404Page.styles.css
When I try to access a page/URL/route that doesn't exist I want to be able to see the 404 page so I can be reminded that the page doesn't exist.
Fixes # 77(issue)
npm run storybook
- [x ] I have performed a self-review of my own code
- [x ] I have made corresponding changes to the documentation
> Add 404page container

- src/client/components/HyfBigLogo/HyfBigLogo.style.css
- src/client/components/SignInButton/Button.css
- src/client/components/SignInButton/Button.js
adding flexbox to CSS file
Fixes #79
> change components styling

- src/client/components/SignInButton/Button.css
- src/client/components/SignInButton/Button.js
- src/client/components/StudyGroupLogo/StudyGroupLogo.styles.css
Fixes #100
tested with storybook
> adjusted sign in button

- src/server/api/routes/api-router.js
- src/server/api/routes/skills.router.js
API skills fixed by fixing typos in the code.
Fixes #150 
Tested in swagger and displaying results from DB.
> API FIXED-skills: updated and working

- src/server/api/controllers/groups.controller.js
testing groups endpoint
Fixes #148 
Postman and Swagger
> groups.controller fixed

- src/client/components/Button/Button.js
- src/client/components/Button/Button.stories.js
- src/client/components/Button/Button.styles.css
Adding appearance prop to button like "default" and "danger" that changes button background color between blue and red
Fixes #176 
It can be tested with storybook
>  Adding appearance prop to button like "default" and "danger"

- src/client/components/Modal/Modal.css
this PR is about changing some css properties in Modal component  .
Fixes # (issue)
> Modal component style improvement

- src/client/components/Appheader/AppHeader.style.css
improved CSS for AppHeader to be more flexible and clearer
Fixes #6 
#7 
tested by storybook
> AppHeader CSS improvement

- src/client/components/EventCardText/EventCardText.js
this PR is about make some changes in EventCardText component .
Fixes # (issue)
> EventCardText improvement 

- src/client/components/ModalWithCancelRegistration/ModalWithCancelRegistration.css
- src/client/components/ModalWithCancelRegistration/ModalWithCancelRegistration.js
- src/client/components/ModalWithCancelRegistration/ModalWithCancelRegistration.stories.js
> Modal View Cancelation/Deletion of Mentor's event registration

- src/client/components/ModalWithFeedback/ModalWithFeedback.css
- src/client/components/ModalWithFeedback/ModalWithFeedback.js
- src/client/components/ModalWithFeedback/ModalWithFeedback.stories.js
Frontend: Modal View for Feedback
Fixes #110 
> modal view for feedback 

- src/client/components/footer/footer.js
- src/client/containers/SignIn/index.js
- src/client/context/userContext.js
In Footer component click on the Profile link or icon to redirect you to the user profile page. Notice, to see whether the user is a student or mentor check userContext.js.
Fixes #87 
got to userContext.js and change setUserRole either to student or mentor. Then click on profile link or icon in the footer.
> linkage in footer to profile page was added

- src/client/components/footer/footer.js
clicking profile will lead you to either student or mentor profile page
Fixes #87 
npm run dev and tested locally
> improve linkage properity

- src/client/App.js
- src/client/components/Auth/AuthenticatedRoute.js
- src/client/containers/SlackAuthPage/SlackAuthPage.component.js
- src/client/containers/SlackAuthPage/SlackAuthPage.styles.css
- src/client/context/userContext.js
- src/client/index.css
- src/server/api/auth/authMiddleware.js
- src/server/api/controllers/slack_users.controller.js
- src/server/api/controllers/users.controller.js
- src/server/api/routes/self.router.js
- src/server/api/routes/slack.router.js
- src/server/app.js
Ensure authentication flow with Slack is possible.
Login with Slack should load the correct data and save it in the context. Authentication middleware in the backend should correctly check for the user when authenticating.
> Authentication flow with Slack

- src/client/components/HyfBigLogo/HyfBigLogo.style.css
- src/client/components/SignInButton/Button.css
- src/client/index.css
> fixing login page style

- src/client/components/HyfBigLogo/HyfBigLogo.style.css
- src/client/components/SignInButton/Button.css
> login page style

- src/client/components/ModalAdminCancelStudentRegistration/ModalAdminCancelStudentRegistration.js
- src/client/components/ModalAdminCancelStudentRegistration/ModalAdminCancelStudentRegistration.stories.js
- src/client/components/ModalAdminCancelStudentRegistration/modalAdminCancelStudentRegistration.css
Create a Modal View for Cancelation/Deletion of student's event registration.
Fixes # (139)
Test in Storybook.
- [ x ] I have performed a self-review of my own code
- [ x ] I have made corresponding changes to the documentation
> Modal View Cancel Student's Registration

- src/client/components/TimeZone/TimeZone.component.js
- src/client/components/TimeZone/TimeZone.stories.js
Time zone component
Fixes #87 
storybook
> time zone component

- src/client/components/footer/footer.js
- src/client/components/footer/footer.stories.js
add Router to footer component
Fixes #87 
storybook
> footer link-Router

- src/server/api/controllers/mentor.controller.js
- src/server/api/routes/api-router.js
- src/server/api/routes/mentor.router.js
create an endpoint for registering mentor
Fixes #216 
swagger and postman
> endpoint for registering mentor

- src/client/App.js
- src/client/components/Logout/Logout.js
Added a new route /logout that will:
When opened call logout from the UserContext.
Once done, redirect to /
Fixes #206 
Tested on browser (added a key on Application->local storage->Key, which is removed on /logout)
> Frontend: Logout route

- src/server/api/controllers/skills.controller.js
- src/server/api/routes/skills.router.js
endpoints for creating, updating, and deleting skills
Fixes # (#220 )
Using swagger
> API: endpoints for creating, updating, and deleting skills

- src/client/components/Dropdown/DropDown.js
- src/client/containers/RegistrationPage/StudentRegistrationPage/StudentRegistrationPage.component.js
This PR is to get the data from the backend using endpoint /api/groups into the student component. I had to change few names and prop types.
Fixes #215 
It is tested with storybook by providing "http://localhost:3000/api/groups " in axios.get(), insted of "/api/groups".
> Student registration page- data from backend using "/api/groups"

- src/server/api/controllers/user.controller.js
- src/server/api/routes/api-router.js
- src/server/api/routes/user.router.js
This API is created to enable the registration of student.
Fixes #103
Swagger
> API:created endpoint to register student

- src/server/api/controllers/events.users.controller.js
- src/server/api/routes/api-router.js
- src/server/api/routes/events.users.router.js
Create an API endpoint that cancels/deletes a specific Mentor's registration on a specific event that is not past.
Fixes #140  (issue)
npm run dev
"http://localhost:3000/api/documentation/"
> mentor registration cancelation

- src/client/containers/RegistrationPage/MentorRegistrationPage/MentorRegistrationPage.component.js
Got the list of organizations for the drop down.
Fixes #217
Can be tested by running the command: 'npm run dev' and entering this url: "http://localhost:3000/registration/mentor" on the browser.
> mentor registration page

- src/client/components/Dropdown/DropDown.js
- src/client/components/Dropdown/DropDown.stories.js
- src/client/components/TimeZone/TimeZone.component.js
- src/client/components/TimeZone/TimeZone.stories.js
change PropTypes in DropDowm component
Fixes #243 
Storybook
> DropDowm Bug fixed

- src/client/components/HelpText/HelpText.css
- src/client/components/HelpText/HelpText.js
- src/client/components/HelpText/HelpText.stories.js
- src/client/containers/RegistrationPage/AdminRegistrationPage/AdminRegistrationPage.component.js
- src/client/containers/RegistrationPage/MentorRegistrationPage/MentorRegistrationPage.component.js
- src/client/containers/RegistrationPage/StudentRegistrationPage/StudentRegistrationPage.component.js
- src/client/containers/SelectionPage/SelectionPage.component.js
Made a new component(HelpText) and updated the pages with the component to replace the custom version.
Fixes #204
Storybook or ' http://localhost:3000/registration/admin '
>  Help Text  Component 

- src/client/components/TimeZone/TimeZone.stories.js
TimeZone.stories.js, Line 29.
Changed value={name} to name={name}
Changed  setValue={setName} to setName={setName} 
Fixes #248 
Storybook.
- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation
- [x ] This PR is ready to be merged and not breaking any other functionality
> TimeZone Bug fix

- src/client/components/CardWithEventsOrStudyGroups/CardWithEventsOrStudyGroups.stories.js
- src/client/components/TimeZone/TimeZone.stories.js
Moved rest of stories to components category
Fixes #250 
storybook
> Moved rest of the stories to components

- src/server/migrations/20210102234000_add_admin_role_to_users.js
This PR is to add a new nullable column to the users table.
Fixes #264 )
Vscode and MySQL workbench
> A new column 'admin_role' added to users table

- src/client/components/Avatar/index.js
- src/client/containers/RegistrationPage/AdminRegistrationPage/AdminRegistrationPage.component.js
- src/client/containers/RegistrationPage/AdminRegistrationPage/AdminRegistrationPage.styles.css
- src/client/containers/RegistrationPage/MentorRegistrationPage/MentorRegistrationPage.component.js
- src/client/containers/RegistrationPage/MentorRegistrationPage/MentorRegistrationPage.styles.css
- src/client/containers/RegistrationPage/Registration.styles.css
- src/client/containers/RegistrationPage/StudentRegistrationPage/StudentRegistrationPage.component.js
- src/client/containers/RegistrationPage/StudentRegistrationPage/StudentRegistrationPage.styles.css
Restyle and align all three registration pages.
See in the actual app.
> Restyle registration pages

- src/client/App.js
- src/client/components/TimeZone/TimeZone.component.js
- src/client/components/TimeZone/TimeZone.stories.js
- src/client/containers/ProfilePage/MentorProfile/MentorProfile.component.js
- src/client/containers/ProfilePage/MentorProfile/MentorProfile.stories.js
- src/client/containers/ProfilePage/MentorProfile/MentorProfile.style.css
- src/client/containers/ProfilePage/ProfilePage.component.js
Mentor Profile page
Fixes #87 
run dev profile/mentor
> Mentor Profile page

- src/client/containers/RegistrationPage/AdminRegistrationPage/AdminRegistrationPage.component.js
- src/client/containers/RegistrationPage/AdminRegistrationPage/AdminRegistrationPage.stories.js
- src/client/containers/RegistrationPage/StudentRegistrationPage/StudentRegistrationPage.component.js
- src/client/utils/formatApiError.js
- src/server/api/auth/requireAuthMiddleware.js
- src/server/api/controllers/user.controller.js
- src/server/api/routes/user.router.js
- src/server/app.js
Add a route for registering an admin and connect to the UI.
Inside the application
> Register admin

- src/client/components/CardWithEventsOrStudyGroups/CardWithEventsOrStudyGroups.styles.css
- src/client/containers/EventsPage/EventsPage.js
- src/client/containers/EventsPage/EventsPage.styles.css
- src/server/api/controllers/events.controller.js
> EventsPage

- src/client/components/Appheader/AppHeader.component.js
- src/client/components/Appheader/AppHeader.style.css
- src/client/components/Button/Button.js
- src/client/components/Button/Button.stories.js
- src/client/components/Button/Button.styles.css
This PR is to add a logout button to the AppHeader component. The button is shown when the user is logged in
Fixes #267 
Tested by adding the component in home page.
here is the screenshot
> App header with logout button
